# pytest.ini is a configuration file used by pytest to control
# how your tests run - without having to type long command-line
# option again and again.
[pytest]
addopts = --browser chromium
testpaths = tests