name: Context Tester
on:
    [workflow_dispatch] # Workflow triggers

jobs:
  test: # Job Name
    runs-on: ubuntu-latest # Runner environment
    steps:
        - name: Output Context
          run: |
            echo "${{ toJSON(github) }}"